version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "mambaforge-4.10"

sphinx:
   configuration: docs/conf.py
   fail_on_warning: true

conda:
  environment: devtools/conda-envs/docs.yml

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
