---
# options for strategist service initialization
init:

  # Time in seconds between strategist iterations.
  # The strategist will query for ready strategies and execute them,
  # then sleep for this duration before the next iteration.
  sleep_interval: 300

  # Maximum number of worker processes for parallel strategy execution.
  # Each strategy execution runs in its own process to avoid blocking.
  max_workers: 4

  # Scopes to limit strategy execution to; defaults to all accessible scopes.
  # If specified, only strategies on networks within these scopes will be executed.
  # Use null or comment out to process all accessible scopes.
  scopes:
    - '*-*-*'

  # LRU cache size for ProtocolDAGResults to reduce object store hits.
  # Higher values improve performance but use more memory.
  cache_size: 1000

  # Neo4j database settings for state store access.
  # If not specified, defaults from environment variables will be used.
  neo4j_settings:
    NEO4J_URL: "neo4j://localhost:7687"
    NEO4J_USER: "neo4j"
    NEO4J_PASS: "password"
    NEO4J_DBNAME: "neo4j"

  # S3 object store settings for ProtocolDAGResult access.
  # If not specified, defaults from environment variables will be used.
  s3_settings:
    AWS_ACCESS_KEY_ID: "your-access-key-id"
    AWS_SECRET_ACCESS_KEY: "your-secret-access-key"
    AWS_SESSION_TOKEN: null
    AWS_S3_BUCKET: "alchemiscale-storage"
    AWS_S3_PREFIX: "results/"
    AWS_DEFAULT_REGION: "us-east-1"

# options for strategist service execution
start:

  # Currently no additional start parameters are supported.
  # This section is reserved for future extensions.